// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dstbwvjvuwoqgjuwtlsx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzdGJ3dmp2dXdvcWdqdXd0bHN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MjUxNTcsImV4cCI6MjA2NTIwMTE1N30.bzP-xPkpiakbglJlJYM5fwgUu0D02ZlJ-0OKG64imP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);